loginapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import PasswordField, SubmitField, StringField
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError, Length
from ..models import Users


class ChangePassword(FlaskForm):

    old_password = PasswordField(label="Old Password",
                                 validators=[DataRequired()])
    new_password = PasswordField(label="New Password",
                                 validators=[DataRequired(),
                                             EqualTo("confirm_new_password", message="Passwords must match!"),
                                             Length(min=6,
                                                    max=30,
                                                    message="Password must be between 6 & 30 characters long!")
                                             ])
    confirm_new_password = PasswordField(label="Confirm New Password",
                                         validators=[DataRequired()])
    submit_btn = SubmitField(label="Change Password")


class ChangeEmail(FlaskForm):

    new_email = StringField(label="New Email",
                            validators=[DataRequired(), Email()])
    password = PasswordField(label="Password",
                             validators=[DataRequired()])
    submit_btn = SubmitField(label="Change Email")

    def validate_new_email(self, field):
        if Users.query.filter_by(email=field.data.lower()).first():
            raise ValidationError("Email already registered!")

loginapp/user/__init__.py
from flask import Blueprint


user = Blueprint("user", __name__)

from . import views, forms

loginapp/user/views.py
from . import user
from flask import render_template, flash, redirect, url_for
from flask_login import login_required, current_user, logout_user
from .forms import ChangePassword, ChangeEmail
from ..models import db
from ..email import send_email


@user.route("/home")
@login_required
def user_home():
    return render_template("user/user_home.html", user=current_user)


@user.route("/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePassword()
    if form.validate_on_submit():
        old_pw = form.old_password.data
        if not current_user.verify_password(old_pw):
            flash("Incorrect password entered! Please try again.",
                  category="error")
            return redirect(url_for("user.change_password"))
        current_user.password = form.new_password.data
        db.session.add(current_user)
        db.session.commit()
        flash("Password changed successfully!",
              category="success")
        return redirect(url_for('user.user_home'))
    return render_template("user/change_password.html", form=form)


@user.route("/change_email", methods=["GET", "POST"])
@login_required
def request_change_email():
    form = ChangeEmail()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            n_email = form.new_email.data.lower()
            token = current_user.generate_email_change_token(new_email=n_email)
            send_email(subject="Email Address Change Request",
                       to=n_email,
                       txt_body="email/email_change.txt",
                       token=token,
                       user=current_user)
            flash("An email with steps to change your email address was sent to your new email.",
                  category="info")
            return redirect(url_for("user.user_home"))
        flash("Invalid email or password",
              category="error")
    return render_template("user/change_email.html", form=form)


@user.route("/change_email/<token>")
@login_required
def change_email(token):
    if current_user.email_change(token):
        db.session.commit()
        flash("Your email has been changed! Please login with your new email id.",
              category="success")
        logout_user()
        return redirect(url_for("auth.login_page"))
    flash("That token is invalid or expired",
          category="error")
    return redirect(url_for("user.user_home"))

loginapp/templates/user/change_email.html
{% extends "base.html" %}

{% block page_title %}Change Email{% endblock page_title %}

{% block navLinks %}
<a class="nav-link" href="{{ url_for('user.user_home') }}">Home</a>
<a class="nav-link mx-4" href="{{ url_for('main.about') }}">About</a>
<a class="nav-link dropdown-toggle mx-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Account
</a>
<ul class="dropdown-menu dropdown-menu-end dropdown-menu-light">
    <li><a class="dropdown-item active" href="{{ url_for('user.request_change_email') }}" aria-current="true">Change Email</a></li>
    <li><a class="dropdown-item" href="{{ url_for('user.change_password') }}">Change Password</a></li>
<!--    <li><a class="dropdown-item" href="#">Another Action</a></li>-->
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a></li>
</ul>
{% endblock navLinks %}

{% block formContainer %}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h2 class="my-4">Let's get you a new email address</h2>
            {{ super() }}
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="mb-3">
                    {% for field, err in form.errors.items() %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <i class="fa-solid fa-triangle-exclamation me-2"></i>
                            {{ err[0] }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>

                <div class="mb-3">
                {{ form.new_email.label(class="form-label") }}
                {{ form.new_email(class="form-control") }}
                </div>

                <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }}
                </div>

                <div class="mt-4 mb-1">
                    {{ form.submit_btn(class="btn btn-primary") }}
                </div>

            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock formContainer %}

loginapp/templates/user/change_password.html
{% extends "base.html" %}

{% block page_title %}Change Password{% endblock page_title %}

{% block navLinks %}
<a class="nav-link" href="{{ url_for('user.user_home') }}">Home</a>
<a class="nav-link mx-4" href="{{ url_for('main.about') }}">About</a>
<a class="nav-link dropdown-toggle mx-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Account
</a>
<ul class="dropdown-menu dropdown-menu-end dropdown-menu-light">
    <li><a class="dropdown-item" href="{{ url_for('user.request_change_email') }}">Change Email</a></li>
    <li><a class="dropdown-item active" href="{{ url_for('user.change_password') }}" aria-current="true">Change Password</a></li>
<!--    <li><a class="dropdown-item" href="#">Another Action</a></li>-->
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a></li>
</ul>
{% endblock navLinks %}

{% block formContainer %}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h2 class="my-4">Let's get you a new password</h2>
            {{ super() }}
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="mb-3">
                    {% for field, err in form.errors.items() %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <i class="fa-solid fa-triangle-exclamation me-2"></i>
                            {{ err[0] }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>

                <div class="mb-3">
                {{ form.old_password.label(class="form-label") }}
                {{ form.old_password(class="form-control") }}
                </div>

                <div class="mb-3">
                {{ form.new_password.label(class="form-label") }}
                {{ form.new_password(class="form-control") }}
                </div>

                <div class="mb-3">
                {{ form.confirm_new_password.label(class="form-label") }}
                {{ form.confirm_new_password(class="form-control") }}
                </div>

                <div class="mt-4 mb-1">
                    {{ form.submit_btn(class="btn btn-primary") }}
                </div>

            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock formContainer %}

loginapp/templates/user/user_home.html
{% extends "base.html" %}

{% block page_title %}Welcome{% endblock page_title %}

{% block navLinks %}
<a class="nav-link active" href="{{ url_for('user.user_home') }}">Home</a>
<a class="nav-link mx-4" href="{{ url_for('main.about') }}">About</a>
<a class="nav-link dropdown-toggle mx-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Account
</a>
<ul class="dropdown-menu dropdown-menu-end dropdown-menu-light">
    <li><a class="dropdown-item" href="{{ url_for('user.request_change_email') }}">Change Email</a></li>
    <li><a class="dropdown-item" href="{{ url_for('user.change_password') }}">Change Password</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log Out</a></li>
</ul>
{% endblock navLinks %}

{% block genericBody %}
<div class="container mt-4">
    <h1>Welcome, {{ user.first_name|capitalize }}!</h1>
</div>
{% endblock genericBody %}